# 自然語言處理

## Jieba 基礎用法

In [1]:
# 引入 Jieba
import jieba

In [2]:
# 載入繁體詞典
jieba.set_dictionary("data/dict.txt.big")

In [3]:
seg_list = jieba.cut("塵世中一個迷途小書僮")
print(" / ".join(seg_list))

Building prefix dict from /Users/fukuballlin/Projects/Hands-on-AI-Tools/data/dict.txt.big ...
Loading model from cache /var/folders/ch/wch8w51d41d5j3yt9tc5tc240000gp/T/jieba.uf1926f5a6d4f9f4491d476b032371238.cache
Loading model cost 0.784 seconds.
Prefix dict has been built succesfully.


塵世 / 中 / 一個 / 迷途 / 小 / 書僮


In [4]:
seg_list = jieba.cut("我們在野生動物園玩")
print(" / ".join(seg_list)) # 歧異詞辨識

我們 / 在 / 野生 / 動物園 / 玩


In [5]:
seg_list = jieba.cut("林志傑是結巴 PHP 的作者")
print(" / ".join(seg_list)) # 新詞辨識

林志傑 / 是 / 結巴 /   / PHP /   / 的 / 作者


In [6]:
# 詞性標注
import jieba.posseg as pseg
words = pseg.cut("颱風就是要泛舟啊不然要幹嘛")
for word, flag in words:
    print('%s %s' % (word, flag))

颱風 ns
就是 d
要 v
泛舟 nz
啊 zg
不然 c
要 v
幹嘛 n


詞性列表請參考 https://gist.github.com/luw2007/6016931

In [7]:
# 實例：中文歌詞斷詞
content = open('data/lyric1.txt', 'rb').read()
print "Input：", content
words = jieba.cut(content)
print(" / ".join(words))

Input： 我沒有心
我沒有真實的自我
我只有消瘦的臉孔
所謂軟弱
所謂的順從一向是我
的座右銘

而我
沒有那海洋的寬闊
我只要熱情的撫摸
所謂空洞
所謂不安全感是我
的墓誌銘

而你
是否和我一般怯懦
是否和我一般矯作
和我一般囉唆

我沒有力
我沒有滿腔的熱火
我只有滿肚的如果
所謂勇氣
所謂的認同感是我
隨便說說

而你
是否和我一般怯懦
是否和我一般矯作
是否對你來說
只是一場遊戲
雖然沒有把握

而你
是否和我一般退縮
是否和我一般肌迫
是否對你來說
我 / 沒有 / 心 / 
 / 我 / 沒有 / 真實 / 的 / 自我 / 
 / 我 / 只有 / 消瘦 / 的 / 臉孔 / 
 / 所謂 / 軟弱 / 
 / 所謂 / 的 / 順從 / 一向 / 是 / 我 / 
 / 的 / 座右銘 / 
 / 
 / 而 / 我 / 
 / 沒有 / 那 / 海洋 / 的 / 寬闊 / 
 / 我 / 只要 / 熱情 / 的 / 撫摸 / 
 / 所謂 / 空洞 / 
 / 所謂 / 不安全感 / 是 / 我 / 
 / 的 / 墓誌銘 / 
 / 
 / 而 / 你 / 
 / 是否 / 和 / 我 / 一般 / 怯懦 / 
 / 是否 / 和 / 我 / 一般 / 矯作 / 
 / 和 / 我 / 一般 / 囉唆 / 
 / 
 / 我 / 沒有 / 力 / 
 / 我 / 沒有 / 滿腔 / 的 / 熱火 / 
 / 我 / 只有 / 滿肚 / 的 / 如果 / 
 / 所謂 / 勇氣 / 
 / 所謂 / 的 / 認同感 / 是 / 我 / 
 / 隨便說說 / 
 / 
 / 而 / 你 / 
 / 是否 / 和 / 我 / 一般 / 怯懦 / 
 / 是否 / 和 / 我 / 一般 / 矯作 / 
 / 是否 / 對 / 你 / 來說 / 
 / 只是 / 一場 / 遊戲 / 
 / 雖然 / 沒有 / 把握 / 
 / 
 / 而 / 你 / 
 / 是否 / 和 / 我 / 一般 / 退縮 / 
 / 是否 / 和 / 我 / 一般 / 肌迫 / 
 / 是否 / 對 / 你 / 來說


In [8]:
# 實例：取出文章中的關鍵詞
import jieba.analyse
content = open('data/lyric1.txt', 'rb').read()
print "Input：", content
tags = jieba.analyse.extract_tags(content, 10)
print "Output："
print(" / ".join(tags))

Input： 我沒有心
我沒有真實的自我
我只有消瘦的臉孔
所謂軟弱
所謂的順從一向是我
的座右銘

而我
沒有那海洋的寬闊
我只要熱情的撫摸
所謂空洞
所謂不安全感是我
的墓誌銘

而你
是否和我一般怯懦
是否和我一般矯作
和我一般囉唆

我沒有力
我沒有滿腔的熱火
我只有滿肚的如果
所謂勇氣
所謂的認同感是我
隨便說說

而你
是否和我一般怯懦
是否和我一般矯作
是否對你來說
只是一場遊戲
雖然沒有把握

而你
是否和我一般退縮
是否和我一般肌迫
是否對你來說
Output：
所謂 / 沒有 / 是否 / 一般 / 矯作 / 來說 / 怯懦 / 墓誌銘 / 退縮 / 寬闊


In [9]:
# 實例：關鍵詞去除停用字
jieba.analyse.set_stop_words("data/stop_words.txt")
content = open('data/lyric1.txt', 'rb').read()
print "Input：", content
tags = jieba.analyse.extract_tags(content, 10)
print "Output："
print(" / ".join(tags))

Input： 我沒有心
我沒有真實的自我
我只有消瘦的臉孔
所謂軟弱
所謂的順從一向是我
的座右銘

而我
沒有那海洋的寬闊
我只要熱情的撫摸
所謂空洞
所謂不安全感是我
的墓誌銘

而你
是否和我一般怯懦
是否和我一般矯作
和我一般囉唆

我沒有力
我沒有滿腔的熱火
我只有滿肚的如果
所謂勇氣
所謂的認同感是我
隨便說說

而你
是否和我一般怯懦
是否和我一般矯作
是否對你來說
只是一場遊戲
雖然沒有把握

而你
是否和我一般退縮
是否和我一般肌迫
是否對你來說
Output：
所謂 / 是否 / 一般 / 矯作 / 來說 / 怯懦 / 墓誌銘 / 退縮 / 寬闊 / 順從


In [10]:
# 實例：台語歌詞斷詞
content = open('data/lyric2.txt', 'rb').read()
print "Input：", content
words = jieba.cut(content)
print(" / ".join(words))

Input： 親愛的媽媽
請你毋通煩惱我
原諒我
行袂開跤
我欲去對抗袂當原諒的人

歹勢啦
愛人啊
袂當陪你去看電影
原諒我
行袂開跤
我欲去對抗欺負咱的人

天色漸漸光
遮有一陣人
為了守護咱的夢
成做更加勇敢的人

已經袂記
是第幾工
請毋通煩惱我
因為阮知道
無行過寒冬
袂有花開的一工

天色漸漸光
天色漸漸光
已經是更加勇敢的人

天色漸漸光
咱就大聲來唱著歌
一直到希望的光線
照光島嶼每一個人

天色漸漸光
咱就大聲來唱著歌
日頭一爬上山
親愛 / 的 / 媽媽 / 
 / 請 / 你 / 毋通 / 煩惱 / 我 / 
 / 原諒 / 我 / 
 / 行袂 / 開跤 / 
 / 我 / 欲 / 去 / 對抗 / 袂 / 當 / 原諒 / 的 / 人 / 
 / 
 / 歹勢 / 啦 / 
 / 愛人 / 啊 / 
 / 袂 / 當 / 陪你去 / 看 / 電影 / 
 / 原諒 / 我 / 
 / 行袂 / 開跤 / 
 / 我 / 欲 / 去 / 對抗 / 欺負 / 咱 / 的 / 人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 遮有 / 一陣 / 人 / 
 / 為 / 了 / 守護 / 咱 / 的 / 夢 / 
 / 成 / 做 / 更加 / 勇敢的人 / 
 / 
 / 已經 / 袂 / 記 / 
 / 是 / 第幾 / 工 / 
 / 請 / 毋通 / 煩惱 / 我 / 
 / 因為 / 阮 / 知道 / 
 / 無行過 / 寒冬 / 
 / 袂 / 有 / 花開 / 的 / 一工 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 天色 / 漸漸 / 光 / 
 / 已經 / 是 / 更加 / 勇敢的人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 咱 / 就 / 大聲 / 來 / 唱 / 著歌 / 
 / 一直 / 到 / 希望 / 的 / 光線 / 
 / 照光 / 島嶼 / 每 / 一個 / 人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 咱 / 就 / 大聲 / 來 / 唱 / 著歌 / 
 / 日頭 / 一爬 / 上山


In [11]:
# 實例：台語歌詞斷詞，使用自定義詞庫
jieba.load_userdict("data/userdict.txt")
content = open('data/lyric2.txt', 'rb').read()
print "Input：", content
words = jieba.cut(content)
print(" / ".join(words))

Input： 親愛的媽媽
請你毋通煩惱我
原諒我
行袂開跤
我欲去對抗袂當原諒的人

歹勢啦
愛人啊
袂當陪你去看電影
原諒我
行袂開跤
我欲去對抗欺負咱的人

天色漸漸光
遮有一陣人
為了守護咱的夢
成做更加勇敢的人

已經袂記
是第幾工
請毋通煩惱我
因為阮知道
無行過寒冬
袂有花開的一工

天色漸漸光
天色漸漸光
已經是更加勇敢的人

天色漸漸光
咱就大聲來唱著歌
一直到希望的光線
照光島嶼每一個人

天色漸漸光
咱就大聲來唱著歌
日頭一爬上山
親愛 / 的 / 媽媽 / 
 / 請 / 你 / 毋通 / 煩惱 / 我 / 
 / 原諒 / 我 / 
 / 行袂開跤 / 
 / 我 / 欲 / 去 / 對抗 / 袂當 / 原諒 / 的 / 人 / 
 / 
 / 歹勢 / 啦 / 
 / 愛人 / 啊 / 
 / 袂當 / 陪你去 / 看 / 電影 / 
 / 原諒 / 我 / 
 / 行袂開跤 / 
 / 我 / 欲 / 去 / 對抗 / 欺負 / 咱 / 的 / 人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 遮有 / 一陣 / 人 / 
 / 為 / 了 / 守護 / 咱 / 的 / 夢 / 
 / 成 / 做 / 更加 / 勇敢的人 / 
 / 
 / 已經 / 袂記 / 
 / 是 / 第幾 / 工 / 
 / 請 / 毋通 / 煩惱 / 我 / 
 / 因為 / 阮 / 知道 / 
 / 無行過 / 寒冬 / 
 / 袂有 / 花開 / 的 / 一工 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 天色 / 漸漸 / 光 / 
 / 已經 / 是 / 更加 / 勇敢的人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 咱 / 就 / 大聲 / 來 / 唱 / 著歌 / 
 / 一直 / 到 / 希望 / 的 / 光線 / 
 / 照光 / 島嶼 / 每 / 一個 / 人 / 
 / 
 / 天色 / 漸漸 / 光 / 
 / 咱 / 就 / 大聲 / 來 / 唱 / 著歌 / 
 / 日頭 / 一爬 / 上山


## LSA 潛在語意分析

### Step 1：中文斷詞，去掉停用字，集合成資料集

In [12]:
stop_words = [u'，', u'你', u'是', u'我', u'的', u'這', u'最美', u'的', u'添加',  u'了', u'如', u'般的', u'中', u'那麼', u'般美', u'般濃', u'很', u'我要', u'達成', u'抓', u'一把', u'開始', u'等待', u'往前', u'向', u'擁抱', u'滿懷', u'到處']
lyrics_dataset = []
with open('data/demo_lyrics.txt') as fp:
    for line in fp:
        words = jieba.cut(line)
        seg_sentence = " / ".join(words)
        print(seg_sentence)
        words = seg_sentence.split(" / ")
        seg_remove_stop_words = []
        for word in words:
            if (word not in stop_words):
                if word != u'\n':
                    seg_remove_stop_words.append(word)
        lyrics_dataset.append(seg_remove_stop_words)
print(lyrics_dataset)

你 / 是 / 我 / 的 / 巧克力 / ， / 你 / 是 / 這 / 世界 / 最美 / 的 / 風景 / 

愛情 / 的 / 甜美 / ， / 添加 / 了 / 你 / 我 / 的 / 理想 / ， / 如 / 巧克力 / 般的 / 快樂 / 滋味 / 

你 / 我 / 的 / 世界 / 中 / ， / 愛情 / 的 / 咖啡 / 那麼 / 甜美 / 

愛情 / 如 / 風景 / 般美 / ， / 愛情 / 如 / 咖啡 / 般濃 / 

愛情 / 的 / 滋味 / 很 / 甜美 / 

我要 / 達成 / 夢想 / 

抓 / 一把 / 陽光 / ， / 夢想 / 開始 / 

等待 / 陽光 / ， / 往前 / 飛翔 / ， / 向 / 夢想 / 

擁抱 / 陽光 / ， / 滿懷 / 理想 / ， / 到處 / 飛翔
[[u'\u5de7\u514b\u529b', u'\u4e16\u754c', u'\u98a8\u666f'], [u'\u611b\u60c5', u'\u751c\u7f8e', u'\u7406\u60f3', u'\u5de7\u514b\u529b', u'\u5feb\u6a02', u'\u6ecb\u5473'], [u'\u4e16\u754c', u'\u611b\u60c5', u'\u5496\u5561', u'\u751c\u7f8e'], [u'\u611b\u60c5', u'\u98a8\u666f', u'\u611b\u60c5', u'\u5496\u5561'], [u'\u611b\u60c5', u'\u6ecb\u5473', u'\u751c\u7f8e'], [u'\u5922\u60f3'], [u'\u967d\u5149', u'\u5922\u60f3'], [u'\u967d\u5149', u'\u98db\u7fd4', u'\u5922\u60f3'], [u'\u967d\u5149', u'\u7406\u60f3', u'\u98db\u7fd4']]


In [13]:
lyrics_dic = []
for seg_remove_stop_words in lyrics_dataset:
    for word in seg_remove_stop_words:
        if word not in lyrics_dic:
            lyrics_dic.append(word)
print(lyrics_dic)

[u'\u5de7\u514b\u529b', u'\u4e16\u754c', u'\u98a8\u666f', u'\u611b\u60c5', u'\u751c\u7f8e', u'\u7406\u60f3', u'\u5feb\u6a02', u'\u6ecb\u5473', u'\u5496\u5561', u'\u5922\u60f3', u'\u967d\u5149', u'\u98db\u7fd4']


In [14]:
for word in lyrics_dic:
    print(word)

巧克力
世界
風景
愛情
甜美
理想
快樂
滋味
咖啡
夢想
陽光
飛翔


### Step 2：將每首歌詞轉成向量表示(doc2vec)

In [15]:
lyrics_dataset_vec = []
for seg_remove_stop_words in lyrics_dataset:
    seg_remove_stop_words_vec = []
    for word in lyrics_dic:
        count = 0
        for word2 in seg_remove_stop_words:
            if word == word2: 
                count = count+1
        seg_remove_stop_words_vec.append(count)
    print(seg_remove_stop_words_vec)
    lyrics_dataset_vec.append(seg_remove_stop_words_vec)
print(lyrics_dataset_vec)

[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]
[[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], [0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]]


### Step 3：LSA 語意分析

In [16]:
import numpy as np
lyrics_dataset_vec = np.array(lyrics_dataset_vec)
print(lyrics_dataset_vec)

[[1 1 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 0 0 1 0 0 0]
 [0 0 1 2 0 0 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 1 1]]


In [17]:
from scipy import linalg, diag, dot
num_dimensions = 2
u, s, vt = linalg.svd(lyrics_dataset_vec)
u = u[:, :num_dimensions]
sigma = diag(s)[:num_dimensions, :num_dimensions]
vt = vt[:num_dimensions, :]
low_rank_document_term_matrix = dot(u, dot(sigma, vt))
print(low_rank_document_term_matrix)

[[ 0.11867629  0.10716535  0.1248784   0.42673089  0.23499908  0.08663343
   0.0896638   0.15684622  0.17401877 -0.0284894  -0.02673936 -0.01668155]
 [ 0.40807287  0.32862817  0.37684866  1.34833923  0.77396951  0.42029799
   0.31840907  0.53500513  0.52614924  0.17497701  0.25081549  0.18944092]
 [ 0.31711724  0.28883819  0.33695866  1.14767727  0.63006568  0.22388123
   0.23896438  0.41938035  0.46949113 -0.09310391 -0.09277046 -0.05992616]
 [ 0.38305077  0.3546717   0.41463648  1.4035487   0.76600755  0.25268271
   0.28718486  0.50720176  0.57757637 -0.15203337 -0.1617535  -0.1081679 ]
 [ 0.28377848  0.24759839  0.28719932  0.99456291  0.55452912  0.23373414
   0.21659606  0.37411315  0.40043287 -0.00886385  0.01048022  0.01369606]
 [ 0.02127003 -0.020197   -0.02956243 -0.04113617  0.00842787  0.13652039
   0.02605044  0.02384445 -0.04019861  0.26468348  0.33401241  0.24096356]
 [ 0.05131676 -0.04290211 -0.06364341 -0.08185678  0.02531442  0.31148481
   0.06137457  0.05815872 -0.086

## Step 4：使用降維後的向量計算 cosin similarity

In [18]:
low_rank_document_term_vec = low_rank_document_term_matrix[0]
print(low_rank_document_term_vec)

[ 0.11867629  0.10716535  0.1248784   0.42673089  0.23499908  0.08663343
  0.0896638   0.15684622  0.17401877 -0.0284894  -0.02673936 -0.01668155]


In [19]:
from scipy import spatial
for vec in low_rank_document_term_matrix:
    score = 1 - spatial.distance.cosine(low_rank_document_term_vec, vec)
    print(score)

1.0
0.96405920759
0.999795153363
0.998286296793
0.996703555514
-0.093506010014
-0.0801314382428
-0.0743859837781
0.0522015275412


In [20]:
low_rank_document_term_vec = low_rank_document_term_matrix[5]
for vec in low_rank_document_term_matrix:
    score = 1 - spatial.distance.cosine(low_rank_document_term_vec, vec)
    print(score)

-0.093506010014
0.17437811112
-0.11363802377
-0.151608348366
-0.0124235605267
1.0
0.999909881114
0.999815914944
0.989380103024


In [21]:
query_vector = lyrics_dataset_vec[0, :]
low_dimensional_query = dot(linalg.inv(sigma), dot(vt, query_vector))
print(low_dimensional_query)

[ 0.16841129  0.02549759]


In [22]:
lsa_query = dot(vt.T, dot(sigma, low_dimensional_query.T))
print(lsa_query)

[ 0.11867629  0.10716535  0.1248784   0.42673089  0.23499908  0.08663343
  0.0896638   0.15684622  0.17401877 -0.0284894  -0.02673936 -0.01668155]


In [23]:
for vec in low_rank_document_term_matrix:
    score = 1 - spatial.distance.cosine(lsa_query, vec)
    print(score)

1.0
0.96405920759
0.999795153363
0.998286296793
0.996703555514
-0.093506010014
-0.0801314382428
-0.0743859837781
0.0522015275412
